plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.2'
    id 'io.spring.dependency-management' version '1.1.4'
}

// 컴파일 옵션 설정
tasks.withType(JavaCompile) {
    options.compilerArgs << "-parameters"
}

repositories {
    mavenCentral()
}

group = 'com.github'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

//instance 문제로 추가
ext {
    set('springCloudVersion', '2021.0.0')
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'
    implementation 'org.springdoc:springdoc-openapi-ui:1.6.9'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'io.jsonwebtoken:jjwt:0.9.1'
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.1.4'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
    implementation 'redis.clients:jedis:5.1.0'
    implementation 'com.github.ulisesbocchio:jasypt-spring-boot-starter:3.0.5'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.assertj:assertj-core:3.23.1'
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.1'
    testImplementation 'junit:junit:4.13.1'
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client:3.1.4'
//    runtimeOnly 'mysql:mysql-connector-java:8.0.28'
    runtimeOnly 'com.h2database:h2'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    //lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    //HTTP servlet
    implementation 'javax.servlet:javax.servlet-api:4.0.1'

    implementation 'org.springdoc:springdoc-openapi-ui:1.7.0'

    //instance 꺼지는 문제
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
//    implementation 'io.netty:netty-resolver-dns-native-macos:4.1.65.Final:osx-x86_64'
    runtimeOnly 'io.netty:netty-resolver-dns-native-macos:4.1.76.Final:osx-aarch_64'
}

//instance 꺼지는 문제
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}



tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('bootJar') {
    mainClass = 'com.github.drug_store_be.DrugStoreBeApplication'
}

jar{
    enabled = false
}