server:
  port:8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://drugstoredb.cn000owqib3s.ap-northeast-2.rds.amazonaws.com:3306/drug_store_db?useUnicode=true&characterEncoding=UTF-8

  jpa:
    show-sql: true

aws:
  s3:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    bucket-name: ${BUCKET_NAME}
    region: ap-northeast-2

jwtpassword:
  source: ${JWT_SECRET_KEY}

  logging:
    level: debug