server:
  port:8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    username: ENC(TGTXnlkPQu5tZnI2EUSF1A==)
    password: ENC(ssiwx5mdhQVVOa0qAmQxgk6Zy9Wff9/E)
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://drugstoredb.cn000owqib3s.ap-northeast-2.rds.amazonaws.com:3306/drug_store_db?useUnicode=true&characterEncoding=UTF-8

  jpa:
    show-sql: true

cloud:
  aws:
    s3:
      credentials:
        access-key: ENC(5o+mxDnFD3CBZRrn53l4t9TG1QxsPmmo0XnfILZhekw=)
        secret-key: ENC(al11oKsyM3Of7h8eecqrKo/XQD10l2cUZi7cJyGZLwLSfFTsmXjRo4s2kQ2RH/rX7HMg6F6ZOp4=)
      bucket-name: ENC(lZ4y3sJbKw6sa1JAnhLHXj2sPoUtYQQr)
      region.static: ENC(RhlVJ6kX8/WBkrD2WSS5TEV2/JWvj0ct)
      stack.auto: false


jasypt:
  encryptor:
    password: ${JASYPT_SECRET_KEY}
    bean: jasyptStringEncryptor

jwtpassword:
  source: ENC(w2RTaxjoAr3LtJK5AtxFGIGrsu6QwayI)

  logging:
    level: debug