server:
  port:8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drug_store_db?useUnicode=true&characterEncoding=UTF-8

  jpa:
    show-sql: true

jwtpassword:
  source: iloveyou

  logging:
    level: debug