server:
  port : 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: "PKCS12"
    key-store-password: ENC(i5PeoNKddffOFHGj/baHbHVAsek6cRQK)

  tomcat:
    redirect-http-to-https: true



spring:
  cache:
    type: simple
  data:
    redis:
      host: ENC(qp5pjAGkUB5jNtNP6kfGWPQOnp3W8BNM)
      port: 6379
      password: ENC(HMxBVpIvWWJRvXy5WQGBOA/wLBGZ6cAy)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(eAnE/Z3zgI6lpVRQgv06n4+F/pDPIJaNIJYgD6Asl9DhEmYpEDGHtH7dIsTnltKr)
            client-secret: ENC(nY4jrovdpVdHeH0VfqHLjhLjqTPwF1RO3+cHyR4LJLownYxDTsVOvStRQtrlFIQ5)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: https://drugstoreproject.shop/oauth2/kakao/callback
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: ENC(Q8tboUYbQTzN6ZdkIsZPOY94EuuHm2BerIGxHQSuq2kVE3htnZolE2A7BKrcdr5R)
            token-uri: ENC(GHMJCEsC8PzOeirF2puhIVaixTZEqSDuLHmFduDjPkpmDDDJN1xDZLNqZq/IJsy6)
            user-info-uri: ENC(K1kG2ttVzPaTaHlPXWShtrSfEKfa9W1Or6RQtNltF585Y6iNOkdqfTc9D58SPNpo)
            user-info-authentication-method: header
            user-name-attribute: id


  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: ENC(pFQU1mumd6kWbx3E5HCxpq+2QZzxNQALpDZN5S0KhMM=)
    password: ENC(N7pFf2aEmgVLUfYjgD4vW7alZcOjQOvFV2hNqy8gq2c=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  datasource:
    username: ENC(TGTXnlkPQu5tZnI2EUSF1A==)
    password: ENC(ssiwx5mdhQVVOa0qAmQxgk6Zy9Wff9/E)
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://drugstoredb.cn000owqib3s.ap-northeast-2.rds.amazonaws.com:3306/drug_store_db?useUnicode=true&characterEncoding=UTF-8

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


cloud:
  aws:
    s3:
      credentials:
        access-key: ENC(5o+mxDnFD3CBZRrn53l4t9TG1QxsPmmo0XnfILZhekw=)
        secret-key: ENC(al11oKsyM3Of7h8eecqrKo/XQD10l2cUZi7cJyGZLwLSfFTsmXjRo4s2kQ2RH/rX7HMg6F6ZOp4=)
      bucket-name: ENC(lZ4y3sJbKw6sa1JAnhLHXj2sPoUtYQQr)
      region.static: ENC(RhlVJ6kX8/WBkrD2WSS5TEV2/JWvj0ct)
      stack.auto: false


jasypt:
  encryptor:
    password: ${JASYPT_SECRET_KEY}
    bean: jasyptStringEncryptor

jwtpassword:
  source: ENC(w2RTaxjoAr3LtJK5AtxFGIGrsu6QwayI)

pay:
  admin-key: ENC(Ysfi34R/drtyXOwIx3USsi57khyAY7y+lMEsBk9KwtuZjo1PpZ/OirmoLBaUxVVA)


  logging:
    level: debug